# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20161015_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Prohibit posting the object.'), (2, 'Block user or ip address indefinitely.')], default=1)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(),
        ),
    ]
