# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_auto_20170116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
