# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20170116_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='regex',
            field=models.BooleanField(default=True),
        ),
    ]
